### PR TITLE
SF-1190: Show All Positions

### PR DESCRIPTION
**Pull request by as472**

### CODE REVIEW

**Comment by taiga7** [comment]
@as472 From a UI consistency perspective, could you please change "Show all positions" to "Show All Positions"?

**Comment by as472** [comment]
> @as472 From a UI consistency perspective, could you please change "Show all positions" to "Show All Positions"?

This has been addressed in the latest changes.

**Comment by biga816** [comment]
@as472 I think the clickable area of the checkbox is too small. The text next to the check box( and some space) should be clickable.
Secured_Finance

**Comment by as472** [comment]
> @as472 I think the clickable area of the checkbox is too small. The text next to the check box( and some space) should be clickable. Secured_Finance

@biga816 , for now I have made the text clickable.

**Review by biga816 — APPROVED** [review]

**Comment by taiga7** [comment]
@as472 
The asset display order in the Active Positions tab is different from the order in the order book. To maintain consistency, please adjust it to match the order in the order book.
For example, on the Arbitrum network, the Active Positions tab currently displays assets in the order ETH, USDC, WBTC. Please change it to display in the order USDC, ETH, WBTC.
Note that I have only tested this on the Arbitrum One network, so please also check other networks.
Screenshot 2024-08-29 0 24 21

**Pull request merged**
