### PR TITLE
Sf 1221 mobile

### PR DESCRIPTION
**Pull request by as472**

### CODE REVIEW

**Comment by leeshuzheng** [comment]
There was some discussion about changing `My Transactions` to `Trade History`, effectively reducing the number of tabs here to 3: https://securedfinance.slack.com/archives/C032N8KUNRZ/p1716539688747709?thread_ts=1716462478.814439&cid=C032N8KUNRZ

Screenshot 2024-07-23 at 5 23 26 PM

This will give your component ample space to display tabs instead of a dropdown in all breakpoints. @as472

**Comment by as472** [comment]
> There was some discussion about changing `My Transactions` to `Trade History`, effectively reducing the number of tabs here to 3: https://securedfinance.slack.com/archives/C032N8KUNRZ/p1716539688747709?thread_ts=1716462478.814439&cid=C032N8KUNRZ
> 
> Screenshot 2024-07-23 at 5 23 26 PM
> 
> This will give your component ample space to display tabs instead of a dropdown in all breakpoints. @as472

1. This PR only converts the existing tables to their new/improved form. This has been communicated clearly in our dev calls/personal calls between Ben, you and me.
2. The dropdowns are a part of the designs. There may be a lot of versions in the designs. I am following these: https://www.figma.com/design/o2wjskNCdkt65haAgWPxo6/Product-UI-(Main)?node-id=16749-19251&m=dev

**Comment by taiga7** [comment]
Please change the name of the Unwind button to Close.
Screenshot 2024-07-24 0 12 08

**Comment by as472** [comment]
> Please change the name of the Unwind button to Close. Screenshot 2024-07-24 0 12 08

it is fixed now! @taiga7

**Review by leeshuzheng — APPROVED** [review]

**Pull request merged**
