### PR TITLE
Sf 1135

### PR DESCRIPTION
**Pull request by leeshuzheng**

### CODE REVIEW

**Comment by biga816** [comment]
@hadilee-sf I can't scroll the new dropdown menu on mobile.
Secured_Finance

**Comment by biga816** [comment]
@leeshuzheng Is there any reason to show only pre-open order books in the dropdown menu of the Pre-Open Order Book page?
Secured_Finance
I think it can provide better UX if it shows all order books the same as the regular order book pages.

**Comment by biga816** [comment]
@leeshuzheng @benk-sf I think we should hide columns that are using data from the subgraph at the non-subgraph-supported chain.
Because users can't know if there is no data or not just supported.

**Comment by leeshuzheng** [comment]
> @leeshuzheng Is there any reason to show only pre-open order books in the dropdown menu of the Pre-Open Order Book page? Secured_Finance I think it can provide better UX if it shows all order books the same as the regular order book pages.

If we show non-itayose markets in the itayose page, the best we can do (when user clicks on these markets) is to direct them to the advanced lending page (`router.push('/')`).

I'm ok with doing that and have started working on it. @benk-sf Let me know if this is okay with you too.

**Review by biga816 — DISMISSED** [review]

**Review by biga816 — APPROVED** [review]

**Pull request merged**
